[package]
name = "sise-atom"
version = "0.2.0"
authors = ["Eduardo Sánchez Muñoz <esm@eduardosm.net>"]
edition = "2018"
description = "Auxiliary functions used to encode and decode SISE atom values."
repository = "https://github.com/eduardosm/rust-sise"
license = "MIT/Apache-2.0"

[dependencies]
